### ISSUE TITLE
Change question format

### ISSUE THREAD

**Issue by leogtzr** [leogtzr/recruitment-interviews#1]
The current question format is:
```
1@Cómo puedes sortear un archivo?@s
```

With that format is difficult to add new fields since the line could be really long.

Something like this would be better:
```
q:begin
id:123
text:How could you sort a file?
level:P
answer:begin
answer:end
q:end
```
or perhaps a YAML format:

```yaml
Questions:
 - id: 1
   question: How do you sort a file?
   level: 1
   Answer: |
    Que pedo
    a ver si jala esto
    arroz

 - id: 2
   question: What is a symlink?
   level: 1
   Answer: |
     Que pedo
     a ver si jala esto
     arroz
```
